apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1UQXlPVEE0TWpRMU5Gb1hEVE16TVRBeU5qQTRNalExTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFRWCmFhWGlzSm9aY0lITXVYaHduNGQ3SHNUOS8yckdqbXQvQ0pENE14QmM5cEQrK2FPQVBGSGk0RUJZNFlUb2lJMkQKcnk3SWpTSzNqamFxcXNSVGlaOEo2TjRPRHJDOWhycmhGenM0aVc3dTNmdThrRVh6R0NDaVhEcTA4SDBTaXpCSQpMcXJzYVM4TmRDZE5TMWVObTBjMXU2dStHaDM4Z3YvZE1QcjE3eHBkZXEram5YSGh2ZnRZMDB2TXpvLzJuWFdxCm4yeE9OS2ZYUGtWYWtzbTV1NFFDR3hRbEIvVjZzSjR3djYzdGxNNVkwWGw4Sm1DT09TZFY5U2NkYTdtS1hrNjcKd3VqdEs0SmUyQnlxNkpMemtsWnRvQUYvSmUrMTFpcFJkY1FrMTBGbVBRS2J0dWJUbldwQXRPOG9TaG5JOVNpMwppYlhvMGJTaXZLV0xMN0JpaXYwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQMytuRmhUVFVROWFscjVCeTNjNnlZOTBHMlNNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSXI0ZWpEcjduakNkTkNybllmbQpEY0RlSEZqMXAzM0JKbS9ZN2hUZDhhRkRtTDNETkRZblZ0dnRkZ0lYdHFudll2UXpZY0xiZlBHSDF5THNFU0lXCmQwVkZnQVpVejlQbDVIbzZRR1lGbW1henBZWjV2ZHlSOWhCMGcwcHBCVElFaEs0VTlqVXVzYU83YkdzWFRzZzgKZy9IeWtOc2w4cE5uREFVdU9WWHIwbEdRN29BRmRPYUYwSGVwQlVNbFNPTndrYlFOcFJFSnZ0TisyNzJPeXFqVQp4aCtCeWVRUWQxTllOQ3NCeWZlaEF5SkRYbkJEZGdYVk4wdzRseFhxVm04d1hlRmMyK3ZBdGdkeDNLdVJSUlZLCi82RVhzaW5IaXRYRldoTlludS83SXlLZ3MwUVBVd2Izck5hRzFxMElWc3pMUkZkQU5mNmttUnB5RHprdWFkcnIKcm1nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://55CF3275A3544A16DD3CEA3B46DB6584.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:238710184079:cluster/udacity-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:238710184079:cluster/udacity-cluster
    namespace: udacity
    user: arn:aws:eks:us-east-2:238710184079:cluster/udacity-cluster
  name: deployment-r
current-context: deployment-r
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:238710184079:cluster/udacity-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - udacity-cluster
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-east-2
      interactiveMode: IfAvailable
      provideClusterInfo: false