name: Deploy Canary
on:
  push:
    branches:
      - main
env:
  EKS_CLUSTER_NAME: udacity-cluster
  AWS_REGION: us-east-2
jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Clone the project
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy Canary 50%
      run: |
        bash starter/apps/canary/canary.sh